---
- hosts: all
  roles:
  - { role: basic }
  - { role: docker }
  - { role: etcd, when: order is defined }
  # etcdctl set ...
  - { role: flannel }

- hosts: k8s-master
  roles:
  - { role: master }

- hosts: k8s-node
  roles:
  - { role: node }
