---
- name: 安装keepalived 
  yum: name={{item}} state=present
  with_items:
        - keepalived

- name: copy keepalived.conf
  template: src=/Users/rnben/Desktop/k8s/roles/keepalived/templates/keepalived.conf.j2   dest=/etc/keepalived/keepalived.conf mode=0755

- name: copy check_haproxy.sh
  copy: src=/Users/rnben/Desktop/k8s/roles/keepalived/files/check_haproxy.sh  dest=/etc/keepalived/check_haproxy.sh mode=0755

- name:  设置keepalived自启动
  service: name=keepalived state=started enabled=yes  daemon_reload=yes
