---
- name: 下载docker-selinux
  copy: src={{base_dir}}/roles/docker/files/docker-ce-selinux-17.03.2.ce-1.el7.centos.noarch.rpm dest=/root/docker-ce-selinux-17.03.2.ce-1.el7.centos.noarch.rpm

- name: 下载docker
  copy: src={{base_dir}}/roles/docker/files/docker-ce-17.03.2.ce-1.el7.centos.x86_64.rpm  dest=/root/docker-ce-17.03.2.ce-1.el7.centos.x86_64.rpm

- name: 安装docker17.3
  shell: yum localinstall -y  docker-ce-selinux-17.03.2.ce-1.el7.centos.noarch.rpm  --nogpgcheck &&   yum localinstall -y docker-ce-17.03.2.ce-1.el7.centos.x86_64.rpm --nogpgcheck

- name: 修改配置文件/usr/lib/systemd/system/docker.service
  lineinfile: dest=/usr/lib/systemd/system/docker.service  regexp='^ExecStart=' line='ExecStart=/usr/bin/dockerd  -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock  --registry-mirror=https://ms3cfraz.mirror.aliyuncs.com'

- name:  设置docker自启动
  service: name=docker state=started enabled=yes  daemon_reload=yes
